scrape_configs:
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['192.168.0.22:9104']  # El servicio MySQL en tu red de Docker
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.0.5:9090']  # Dirección IP de Prometheus
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.0.7:8080']  # Dirección IP del contenedor cAdvisor
