version: '3.8'

services:
  frontend:
    image: fernandovalero/frontend-imagen:v1  # Asegúrate de que esta ruta sea correcta
    ports:
      - "4200:80"  # Asegúrate de mapear correctamente el puerto 4200
    networks:
      - my-network

  backend:
    image: fernandovalero/backend-imagen:v1
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root  # Usuario de la base de datos
      - DB_PASSWORD=root  # Contraseña de la base de datos
      - DB_NAME=tpf_db_d  # Nombre de la base de datos
    depends_on:
      - mysql
    networks:
      - my-network
    ports:
      - "3000:3000"

  mysql:
    image: mysql:latest  # Imagen oficial de MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root  # Contraseña del root
      #MYSQL_USER: root  # Usuario de la base de datos
      #MYSQL_PASSWORD: PVisual23/9-  # Contraseña de la base de datos
      MYSQL_DATABASE: tpf_db_d  # Nombre de la base de datos
    volumes:
      - mysql-data:/var/lib/mysql  # Volumen persistente para los datos
    networks:
      - my-network
    ports:
      - "3307:3306"  # Exponer el puerto 3306 para conexiones externas
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest  # Imagen oficial de phpMyAdmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  # Nombre del servicio MySQL definido arriba
      PMA_PORT: 3306   # Puerto del servicio MySQL
      MYSQL_ROOT_PASSWORD: root  # Contraseña del root
    depends_on:
      - mysql
    networks:
      - my-network
    ports:
      - "8080:80"  # Puerto para acceder a phpMyAdmin desde el navegador


networks:
  my-network:

volumes:
  mysql-data:
  mysql-backups:  # Volumen específico para backups