name: CI/CD Local Deployment

on:
  push:
    branches:
      - main  # Detecta cambios en la rama principal

jobs:
  deploy:
    runs-on: self-hosted  # Usa el runner en tu máquina local

    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker para usar Docker Hub (si es necesario)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Iniciar sesión en Docker Hub (necesitarás tus credenciales)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Configura tu nombre de usuario en los secrets de GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Configura tu contraseña en los secrets de GitHub

      # 4. Construir las imágenes Docker
      - name: Build Docker images
        run: |
          # Construir imagen del frontend
          docker build -t fernandovalero/frontend-imagen:latest ./tpf-frontend
          # Construir imagen del backend
          docker build -t fernandovalero/backend-imagen:latest ./tpf-backend

      # 5. Subir las imágenes a Docker Hub
      - name: Push Docker images to Docker Hub
        run: |
          # Subir imagen del frontend
          docker push fernandovalero/frontend-imagen:latest
          # Subir imagen del backend
          docker push fernandovalero/backend-imagen:latest

      # 6. Actualizar contenedores con el archivo docker-compose
      - name: Deploy containers
        run: |
          docker-compose down --volumes --remove-orphans  
          docker-compose pull  
          docker-compose up -d --build
