name: CI/CD Local Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Usa el runner en tu máquina local
    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Actualizar imágenes desde Docker Hub
      - name: Pull Docker images
        run: |
          docker pull fernandovalero/frontend-imagen:v1
          docker pull fernandovalero/backend-imagen:v1

      # 3. Actualizar contenedores con el archivo del repositorio
      - name: Deploy containers
        run: |
          docker-compose down
          docker-compose up -d
