name: CI/CD Local Deployment

on:
  push:
    branches:
      - main  # Detecta cambios en la rama principal

jobs:
  deploy:
    runs-on: self-hosted  # Usa el runner en tu máquina local

    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Actualizar imágenes desde Docker Hub
      - name: Pull Docker images
        run: |
          docker pull fernandovalero/frontend-imagen:latest
          docker pull fernandovalero/backend-imagen:latest

      # 3. Actualizar contenedores con el archivo del repositorio
      - name: Deploy containers
        run: |
          docker-compose down --volumes --remove-orphans  
          docker-compose pull  
          docker-compose up -d --build  
